// <auto-generated />
using LojaManoel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaManoel.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20250528131658_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaManoel.Models.Caixa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("caixa_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dimensoesid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("dimensoesid");

                    b.ToTable("Caixa");
                });

            modelBuilder.Entity("LojaManoel.Models.Dimensoes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("altura")
                        .HasColumnType("int");

                    b.Property<int>("comprimento")
                        .HasColumnType("int");

                    b.Property<int>("largura")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("LojaManoel.Models.Caixa", b =>
                {
                    b.HasOne("LojaManoel.Models.Dimensoes", "dimensoes")
                        .WithMany()
                        .HasForeignKey("dimensoesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dimensoes");
                });
#pragma warning restore 612, 618
        }
    }
}
